language: go

go:
  - tip

sudo: required

services:
  - docker

script:
  - make dockerbuild

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push factlist/factlist-api;
    fi
